- name: Configure address objects on Palo Alto devices using Vault
  hosts: paloalto
  gather_facts: no

  vars_files:
    - vault.yml

  vars:
    provider:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Show address objects variable
      debug:
        var: address_objects

    - name: Ensure address objects are configured
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ provider }}"
        name: "{{ item.name }}"
        value: "{{ item.ip }}"
        description: "Provisioned by Ansible with Vault"
        address_type: "ip-netmask"
      loop: "{{ address_objects }}"