- name: Configure loopback interfaces on Cisco router
  hosts: cisco
  gather_facts: no
  connection: network_cli

  vars:
    loopbacks:
      - id: 1
        ip: 192.0.2.1
      - id: 2
        ip: 192.0.2.2
      - id: 3
        ip: 192.0.2.3
      - id: 4
        ip: 192.0.2.4

  tasks:
  - name: Configure even-numbered loopbacks only
    cisco.ios.ios_config:
      lines:
        - interface Loopback{{ item.id }}
        - ip address {{ item.ip }} 255.255.255.255
    loop: "{{ loopbacks }}"
    when: (item.id | int) is divisibleby 2
