---
- name: Show NTP settings from Cisco devices
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather Cisco facts
      ios_facts:

    - name: Print Cisco hostname
      debug:
        var: ansible_net_hostname

    - name: Print Cisco NTP servers
      debug:
        var: ansible_net_ntp

---
- name: Check NTP configuration on Palo Alto device
  hosts: paloalto
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Get current NTP configuration from Palo Alto
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<show><ntp><servers></servers></ntp></show>"
      register: ntp_output

    - name: Print configured NTP servers
      debug:
        var: ntp_output.stdout