---
- name: Show NTP settings from Cisco devices
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Gather Cisco facts
      ios_facts:

    - name: Show NTP configuration on Cisco device
      ios_command:
        commands:
          - show run | include ntp
      register: ntp_output

    - name: Print NTP configuration
      debug:
        var: ntp_output.stdout_lines

- name: Check NTP configuration on Palo Alto device
  hosts: paloalto
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

  tasks:
    - name: Get current NTP configuration from Palo Alto
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "show ntp"
      register: ntp_output
    
    - name: Print configured NTP servers
      debug:
        var: ntp_output.stdout