---
- name: Print all facts from Cisco and Palo Alto devices
  hosts: all
  tasks:
    - name: Print all Cisco facts
      debug:
        var: ansible_facts
      when: ansible_network_os == 'ios'

    - name: Print all Palo Alto facts
      debug:
        var: ansible_facts
      when: ansible_network_os == 'paloaltonetworks.panos.panos'